import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {unpackGLB,geometryScene} from '../scripts/gltf-tools.mjs';
import {reflectionZone,transmissionScale,createDaylightPanorama} from '../lib/reflections';
import {Mesh,MeshPhysicalMaterial} from 'three';
const j=unpackGLB(readFileSync('public/assets/farmhouse_visual.glb')).json;
test('source metals retain metallic response and recovered procedural roughness',()=>{for(const name of ['R4_Chrome','R4_Steel_Stainless','R4_Brass_Satin']){const m=j.materials.find((m:any)=>m.name===name);assert.ok(m.pbrMetallicRoughness.metallicFactor>.8,name);assert.ok(m.pbrMetallicRoughness.roughnessFactor<.35,name+' flattened roughness');}const mirror=j.materials.find((m:any)=>m.name==='R4_Mirror');assert.ok((mirror.pbrMetallicRoughness.metallicFactor??1)>.9);assert.ok(mirror.pbrMetallicRoughness.roughnessFactor<.02);});
test('clear smoked and frosted glass carry real transmission volume and IOR',()=>{for(const name of ['R4_Glass_Clear','R4_Glass_Smoked','R4_Glass_Frosted']){const m=j.materials.find((m:any)=>m.name===name);assert.equal(m.pbrMetallicRoughness.metallicFactor,0);assert.equal(m.alphaMode,'OPAQUE');assert.equal(m.pbrMetallicRoughness.baseColorFactor[3],1);assert.equal(m.extensions.KHR_materials_transmission.transmissionFactor,1);assert.equal(m.extensions.KHR_materials_volume.thicknessFactor,.02);assert.ok(m.extensions.KHR_materials_ior.ior>=1.45);}});
test('GLTFLoader actually creates transmissive physical glass, not alpha paint',async()=>{const s=await geometryScene(readFileSync('public/assets/farmhouse_visual.glb'));const found=new Map();s.traverse(o=>{if(o instanceof Mesh)for(const m of Array.isArray(o.material)?o.material:[o.material])if(['R4_Glass_Clear','R4_Glass_Smoked','R4_Glass_Frosted'].includes(m.name))found.set(m.name,m);});assert.equal(found.size,3);for(const [name,m] of found){assert.ok(m instanceof MeshPhysicalMaterial,name);assert.equal(m.transmission,1);assert.equal(m.opacity,1);assert.equal(m.thickness,.02);}});
test('all quality levels keep glass, reducing refraction resolution instead',()=>{assert.equal(transmissionScale('LOW'),.35);assert.equal(transmissionScale('MEDIUM'),.5);assert.equal(transmissionScale('HIGH'),1);assert.equal(transmissionScale('ULTRA'),1);for(const p of [{x:12,y:1,z:-20},{x:12,y:7,z:-5},{x:36,y:8,z:16}])assert.equal(reflectionZone(p),'exterior');for(const p of [{x:12,y:1,z:-5},{x:36,y:1,z:16},{x:-28,y:1,z:28}])assert.equal(reflectionZone(p),'interior');});

test('daylight reflection radiance stays bounded and preserves surface color',()=>{const texture=createDaylightPanorama();const data=texture.image.data as Float32Array;let peak=0,sum=0,n=0;for(let i=0;i<data.length;i+=4){peak=Math.max(peak,data[i],data[i+1],data[i+2]);sum+=(data[i]+data[i+1]+data[i+2])/3;n++;}assert.ok(peak<9.5);assert.ok(sum/n>.1&&sum/n<1);texture.dispose();});
